import React from 'react';
import {Tabs, Tab} from 'material-ui/Tabs';
// From https://github.com/oliviertassinari/react-swipeable-views
import SwipeableViews from 'react-swipeable-views';
import FoodGroupTab from './FoodGroupTab';
import AutoComplete from 'material-ui/AutoComplete';
import FoodCard from './FoodCard';
import FlatButton from 'material-ui/FlatButton';
import RaisedButton from 'material-ui/RaisedButton';
import ReactCSSTransitionGroup from 'react-addons-css-transition-group';

const foods = [
  'Bread (White)', 'Bread (Wholemeal)', 'Bread (Wholegrain)', 'Burger Bun',
  'Brown Rice (Raw)', 'White Rice (Raw)', 'Jasmine Rice (Raw)', 'Basmati Rice (Raw)', 'Cereal (Special K)',
  'Cereal (Cocopops)', 'Cereal (RiceBubbles)', 'Cereal (CornFlakes)', 'Pita Bread', 'Naan Bread', 'Porridge',
  'Macaroni (Raw)', 'Spaghetti (Raw)', 'Spaghetti (Canned)', 'Weet-bix', 'Couscous (Raw)',
  'Kidney Bean', 'Broad Bean', 'Baked Beans', 'Fish (Salmon)', 'Tuna (Canned)', 'Chicken (Canned)', 'Steak',
  'Egg', 'Sausage', 'Bacon', 'Ham', 'Chicken (Thigh)', 'Chicken (Wing)', 'Chicken (Breast)', 'Chia Seed', 'Linseed (Flax Seed)', 'Sunflower Seed', 'Tofu', 'Chickpea', 'Nuts (Almond)',
  'Nuts (Cashew)', 'Nuts (Pistachio)', 'Nuts (Walnut)', 'Nuts (Macademia)', 'Banana', 'Apple', 'Peach (Canned)', 'Pear (Canned)', 'Orange', 'Salad Greens', 'Blueberry', 'Raspberry',
  'Blackberry', 'Strawberry', 'Kiwifruit', 'Apricot', 'Pineapple', 'Pear (Nashi)', 'Watermelon', 'Rockmelon', 'Mango', 'Papaya',
  'Capsicum', 'Grape', 'Apricot (Dried)', 'Raisin (Dried)', 'Prune (Dried)', 'Onion', 'Tomato', 'Corn', 'Broccoli', 'Carrot', 'Potato', 'Pumpkin',
  'Yoghurt','Cheese (Mozzarella)', 'Cheese (Parmesan)', 'Cheese (Cheddar)', 'Milk (Trim)', 'Milk (Full fat)',
  'Paneer', 'Cheese (Feta)', 'Cream Cheese', 'Muffin', 'Chips', 'Pringles', 'Shapes', 'Brownie', 'Apple Pie',
  'Ice Cream Cone', 'Lasagna', 'Pizza', 'Muesli Bar', 'Tim tams', 'Steak and cheese pie', 'Cup ramen', 'Chicken nuggets', 'French Fries',
  'Oil', 'Butter', 'Salad dressing', 'Up and Go', 'Water', 'Wine', 'Spirits', 'Beer', 'Coke', 'Diet Coke', 'Sprite', 'Coconut water', 'Coconut Milk', 'Almond Milk', 'Soy Milk',
];

const styles = {
  headline: {
    fontSize: 24,
    paddingTop: 16,
    marginBottom: 12,
    fontWeight: 400,
  },
  slide: {
    padding: 10,
  },
};

const FoodMap = {
  'bread (white)': [{
    name: 'Bread (White)',
    calories: '66 calories',
    fat: '0.82g',
    carb: '12.65g',
    protein: '1.91g',
    portionSize: '1 slice',
    grams: '42.5g',
    image: require('../public/images/white_bread.jpg'),
    category: 'Bread and cereals',
    codeName: 'whiteBread'
  }],
  'bread (wholemeal)': [{
    name: 'Bread (Wholemeal)',
    calories: '128 calories',
    fat: '2.48g',
    carb: '23.64g',
    protein: '3.86g',
    portionSize: '1 slice',
    grams: '42.5g',
    image: require('../public/images/wholemeal_bread.jpg'),
    category: 'Bread and cereals',
    codeName: 'wholemealBread'
  }],
  'bread (wholegrain)': [{
    name: 'Bread (Wholegrain)',
    calories: '65 calories',
    fat: '0.99g',
    carb: '12.06g',
    protein: '2.6g',
    portionSize: '1 slice',
    grams: '42.5g',
    image: require('../public/images/wholegrain_bread.jpg'),
    category: 'Bread and cereals',
    codeName: 'wholegrainBread'
  }],
  'burger bun': [{
    name: 'Burger Bun',
    calories: '120 calories',
    fat: '1.5g',
    carb: '23g',
    protein: '4g',
    portionSize: '1 slice',
    grams: '43g',
    image: require('../public/images/burger_bun.jpg'),
    category: 'Bread and cereals',
    codeName: 'burgerBun'
  }],
  'brown rice (raw)': [{
    name: 'Brown Rice (Raw)',
    calories: '344 calories',
    fat: '2.05g',
    carb: '72.37g',
    protein: '7.13g',
    portionSize: '1/2 cup',
    grams: '87g',
    image: require('../public/images/brown_rice.jpg'),
    category: 'Bread and cereals',
    codeName: 'brownRice'
  }],
  'white rice (raw)': [{
    name: 'White Rice (Raw)',
    calories: '351 calories',
    fat: '0.61g',
    carb: '77.36g',
    protein: '6.44g',
    portionSize: '1/2 cup',
    grams: '87g',
    image: require('../public/images/white_rice.jpg'),
    category: 'Bread and cereals',
    codeName: 'whiteRice'
  }],
  'jasmine rice (raw)': [{
    name: 'Jasmine Rice (Raw)',
    calories: '360 calories',
    fat: '1.6g',
    carb: '94g',
    protein: '6g',
    portionSize: '1/2 cup',
    grams: '63g',
    image: require('../public/images/jasmine_rice.jpg'),
    category: 'Bread and cereals',
    codeName: 'jasmineRice'
  }],
  'basmati rice (raw)': [{
    name: 'Basmati Rice (Raw)',
    calories: '320 calories',
    fat: '2.5g',
    carb: '72g',
    protein: '6g',
    portionSize: '1/2 cup',
    grams: '89.3g',
    image: require('../public/images/basmati_rice.jpg'),
    category: 'Bread and cereals',
    codeName: 'basmatiRice'
  }],
  'cereal (special k)': [{
    name: 'Cereal (Special K)',
    calories: '117 calories',
    fat: '0.48g',
    carb: '22.01g',
    protein: '6.98g',
    portionSize: '1 cup',
    grams: '30.87g',
    image: require('../public/images/special_k.jpg'),
    category: 'Bread and cereals',
    codeName: 'specialK'
  }],
  'cereal (rice bubbles)': [{
    name: 'Cereal (Rice bubbles)',
    calories: '112 calories',
    fat: '0.1g',
    carb: '26g',
    protein: '1.9g',
    portionSize: '1 cup',
    grams: '35g',
    image: require('../public/images/rice_bubbles.jpg'),
    category: 'Bread and cereals',
    codeName: 'riceBubbles'
  }],
  'cereal (cocopops)': [{
    name: 'Cereal (Cocopops)',
    calories: '116.7 calories',
    fat: '0.1g',
    carb: '26.5g',
    protein: '1.4g',
    portionSize: '3/4 cup',
    grams: '30g',
    image: require('../public/images/cocopops.jpg'),
    category: 'Bread and cereals',
    codeName: 'cocopops'
  }],
  'cereal (cornflakes)': [{
    name: 'Cereal (Cornflakes)',
    calories: '100 calories',
    fat: '0g',
    carb: '24g',
    protein: '2g',
    portionSize: '1 cup',
    grams: '28g',
    image: require('../public/images/corn_flakes.jpg'),
    category: 'Bread and cereals',
    codeName: 'cornFlakes'
  }],
  'pita bread': [{
    name: 'Pita Bread',
    calories: '165 calories',
    fat: '0.7g',
    carb: '33.4g',
    protein: '5.5g',
    portionSize: '1 Pita',
    grams: '60g',
    image: require('../public/images/pita_bread.jpg'),
    category: 'Bread and cereals',
    codeName: 'pitaBread'
  }],
  'naan bread': [{
    name: 'Naan Bread',
    calories: '230 calories',
    fat: '4g',
    carb: '40g',
    protein: '8g',
    portionSize: '1 Naan',
    grams: '92g',
    image: require('../public/images/naan_bread.jpg'),
    category: 'Bread and cereals',
    codeName: 'naanBread'
  }],
  'porridge': [{
    name: 'Porridge',
    calories: '120 calories',
    fat: '2.5g',
    carb: '21g',
    protein: '6g',
    portionSize: '1/3 cup',
    grams: '35g',
    image: require('../public/images/porridge.jpg'),
    category: 'Bread and cereals',
    codeName: 'porridge'
  }],
  'macaroni (raw)': [{
    name: 'Macaroni Pasta (Raw)',
    calories: '150 calories',
    fat: '6.5g',
    carb: '20g',
    protein: '2.5g',
    portionSize: '1/2 cup',
    grams: '37.5g',
    image: require('../public/images/macaroni.jpg'),
    category: 'Bread and cereals',
    codeName: 'macaroni'
  }],
  'spiral pasta (raw)': [{
    name: 'Spiral Pasta (Raw)',
    calories: '300 calories',
    fat: '11g',
    carb: '40g',
    protein: '5g',
    portionSize: '1 cup',
    grams: '65g',
    image: require('../public/images/spiral_pasta.jpg'),
    category: 'Bread and cereals',
    codeName: 'spiral_pasta'
  }],
  'spaghetti (raw)': [{
    name: 'Spaghetti (Raw)',
    calories: '210 calories',
    fat: '2.5g',
    carb: '40g',
    protein: '8g',
    portionSize: 'Diameter of a 50 cent coin',
    grams: '56g',
    image: require('../public/images/spaghetti.jpg'),
    category: 'Bread and cereals',
    codeName: 'spaghetti'
  }],
  'spaghetti (canned)': [{
    name: 'Spaghetti (Canned)',
    calories: '120 calories',
    fat: '0.4g',
    carb: '25.3g',
    protein: '3.4g',
    portionSize: '1/2 can',
    grams: '400g',
    image: require('../public/images/spaghetti_canned.jpg'),
    category: 'Bread and cereals',
    codeName: 'spaghettiCanned'
  }],
  'weet-bix': [{
    name: 'Weet-bix',
    calories: '107 calories',
    fat: '0.4g',
    carb: '20.1g',
    protein: '3.7g',
    portionSize: '2 biscuits',
    grams: '30g',
    image: require('../public/images/weetbix.jpg'),
    category: 'Bread and cereals',
    codeName: 'weetbix'
  }],
  'couscous (raw)': [{
    name: 'Couscous (Raw)',
    calories: '376.3 calories',
    fat: '0.64g',
    carb: '77.46g',
    protein: '12.77g',
    portionSize: '2/3 cup',
    grams: '100g',
    image: require('../public/images/couscous.jpg'),
    category: 'Bread and cereals',
    codeName: 'couscous'
  }],
  'kidney bean': [{
    name: 'Kidney Bean',
    calories: '112 calories',
    fat: '0g',
    carb: '20g',
    protein: '8g',
    portionSize: '1/2 cup',
    grams: '89g',
    image: require('../public/images/kidney_bean.jpg'),
    category: 'Protein Foods',
  }],
  'broad bean': [{
    name: 'Broad Bean',
    calories: '512 calories',
    fat: '2.3g',
    carb: '87.43g',
    protein: '39.18g',
    portionSize: '1 cup',
    grams: '150g',
    image: require('../public/images/broad_bean.jpg'),
    category: 'Protein Foods',
  }],
  'baked beans': [{
    name: 'Baked Beans',
    calories: '130 calories',
    fat: '0.5g',
    carb: '26g',
    protein: '6g',
    portionSize: '1/2 cup',
    grams: '129g',
    image: require('../public/images/baked_beans.jpg'),
    category: 'Protein Foods',
  }],
  'fish (salmon)': [{
    name: 'Fish (Salmon)',
    calories: '120 calories',
    fat: '7.5g',
    carb: '0g',
    protein: '11.5g',
    portionSize: '1/2 Fillet',
    grams: '56.5g',
    image: require('../public/images/salmon.jpg'),
    category: 'Protein Foods',
  }],
  'tuna (canned)': [{
    name: 'Tuna (Canned)',
    calories: '60 calories',
    fat: '1g',
    carb: '0g',
    protein: '13g',
    portionSize: '1/4 cup',
    grams: '56g',
    image: require('../public/images/tuna.jpg'),
    category: 'Protein Foods',
  }],
  'chicken (canned)': [{
    name: 'Chicken (Canned)',
    calories: '70 calories',
    fat: '1.5g',
    carb: '0g',
    protein: '12g',
    portionSize: '1/3 cup',
    grams: '71g',
    image: require('../public/images/chicken_canned.jpg'),
    category: 'Protein Foods',
  }],
  'steak': [{
    name: 'Steak',
    calories: '135 calories',
    fat: '9g',
    carb: '0g',
    protein: '13.5g',
    portionSize: 'Area of a deck of cards',
    grams: '85.05g',
    image: require('../public/images/steak.jpg'),
    category: 'Protein Foods',
  }],
  'egg': [{
    name: 'Egg',
    calories: '70 calories',
    fat: '5g',
    carb: '1g',
    protein: '6g',
    portionSize: '1 large egg',
    grams: '53g',
    image: require('../public/images/egg.jpg'),
    category: 'Protein Foods',
  }],
  'sausage': [{
    name: 'Sausage',
    calories: '170 calories',
    fat: '14.86g',
    carb: '0g',
    protein: '8.45g',
    portionSize: '2 links',
    grams: '55.92g',
    image: require('../public/images/sausage.jpg'),
    category: 'Protein Foods',
  }],
  'bacon': [{
    name: 'Bacon',
    calories: '60 calories',
    fat: '5g',
    carb: '0g',
    protein: '5g',
    portionSize: '3 slices',
    grams: '14g',
    image: require('../public/images/bacon.jpg'),
    category: 'Protein Foods',
  }],
  'ham': [{
    name: 'Ham',
    calories: '60 calories',
    fat: '5g',
    carb: '0g',
    protein: '5g',
    portionSize: '3 slices',
    grams: '14g',
    image: require('../public/images/ham.jpg'),
    category: 'Protein Foods',
  }],
  'chicken (wing)': [{
    name: 'Chicken (Wing)',
    calories: '60 calories',
    fat: '5g',
    carb: '0g',
    protein: '5g',
    portionSize: '3 slices',
    grams: '14g',
    image: require('../public/images/chicken_wing.jpg'),
    category: 'Protein Foods',
  }],
  'chicken (breast)': [{
    name: 'Chicken (Breast)',
    calories: '135 calories',
    fat: '4g (6g with skin)',
    carb: '0g',
    protein: '21g',
    portionSize: 'Area of a deck of cards',
    grams: '85.05g',
    image: require('../public/images/chicken_breast.jpg'),
    category: 'Protein Foods',
  }],
  'chicken (thigh)': [{
    name: 'Chicken (Thigh)',
    calories: '170 calories',
    fat: '7g',
    carb: '0g',
    protein: '19g',
    portionSize: '1 thigh',
    grams: '85.05g',
    image: require('../public/images/chicken_thigh.jpg'),
    category: 'Protein Foods',
  }],
  'chia seed': [{
    name: 'Chia Seed',
    calories: '68 calories',
    fat: '4.5g',
    carb: '6g',
    protein: '2g',
    portionSize: '1 tablespoon',
    grams: '10g',
    image: require('../public/images/chia.jpg'),
    category: 'Protein Foods',
  }],
  'linseed (flax seed)': [{
    name: 'Linseed (Flax Seed)',
    calories: '70 calories',
    fat: '5.6g',
    carb: '4g',
    protein: '3g',
    portionSize: '2 tablespoon',
    grams: '14g',
    image: require('../public/images/linseed.jpg'),
    category: 'Protein Foods',
  }],
  'sunflower seed': [{
    name: 'Sunflower Seed',
    calories: '150 calories',
    fat: '11g',
    carb: '7g',
    protein: '6g',
    portionSize: '1/4 Cup',
    grams: '31g',
    image: require('../public/images/sunflower_seed.jpg'),
    category: 'Protein Foods',
  }],
  'tofu': [{
    name: 'Tofu',
    calories: '110 calories',
    fat: '3g',
    carb: '4g',
    protein: '17g',
    portionSize: '1/3 Cup',
    grams: '85g',
    image: require('../public/images/tofu.jpg'),
    category: 'Protein Foods',
  }],
  'chickpea': [{
    name: 'Chickpea',
    calories: '130 calories',
    fat: '2g',
    carb: '22g',
    protein: '7g',
    portionSize: '1/2 Cup',
    grams: '82g',
    image: require('../public/images/chickpea.png'),
    category: 'Protein Foods',
  }],
  'nuts (almond)': [{
    name: 'Nuts (Almond)',
    calories: '160 calories',
    fat: '14g',
    carb: '6g',
    protein: '6g',
    portionSize: '23 Kernels',
    grams: '28g',
    image: require('../public/images/almond.jpg'),
    category: 'Protein Foods',
  }],
  'nuts (cashew)': [{
    name: 'Nuts (Cashew)',
    calories: '156 calories',
    fat: '12g',
    carb: '9g',
    protein: '5g',
    portionSize: '18 Kernels',
    grams: '28g',
    image: require('../public/images/cashew.jpg'),
    category: 'Protein Foods',
  }],
  'nuts (pistachio)': [{
    name: 'Nuts (Pistachio)',
    calories: '170 calories',
    fat: '13g',
    carb: '5g',
    protein: '6g',
    portionSize: '43 Kernels',
    grams: '28g',
    image: require('../public/images/pistachio.jpg'),
    category: 'Protein Foods',
  }],
  'nuts (walnut)': [{
    name: 'Nuts (Walnut)',
    calories: '170 calories',
    fat: '16g',
    carb: '5g',
    protein: '5g',
    portionSize: '14 Halves',
    grams: '28g',
    image: require('../public/images/walnut.jpg'),
    category: 'Protein Foods',
  }],
  'nuts (macademia)': [{
    name: 'Nuts (Macademia)',
    calories: '204 calories',
    fat: '21.48g',
    carb: '3.92g',
    protein: '2.24g',
    portionSize: '12 Kernels',
    grams: '28g',
    image: require('../public/images/macademia.jpg'),
    category: 'Protein Foods',
  }],
  'banana': [{
    name: 'Banana',
    calories: '110 calories',
    fat: '0g',
    carb: '30g',
    protein: '1g',
    portionSize: '1 Medium banana',
    grams: '126g',
    image: require('../public/images/banana.jpg'),
    category: 'Fruits and vegetables',
  }],
  'apple': [{
    name: 'Apple',
    calories: '130 calories',
    fat: '0g',
    carb: '34g',
    protein: '1g',
    portionSize: '1 Large apple',
    grams: '242g',
    image: require('../public/images/apple.jpg'),
    category: 'Fruits and vegetables',
  }],
  'peach (canned)': [{
    name: 'Peach (Canned)',
    calories: '70 calories',
    fat: '0g',
    carb: '17g',
    protein: '1g',
    portionSize: '1/2 Cup',
    grams: '242g',
    image: require('../public/images/canned_peach.jpg'),
    category: 'Fruits and vegetables',
  }],
  'pear (canned)': [{
    name: 'Pear (Canned)',
    calories: '60 calories',
    fat: '0g',
    carb: '15g',
    protein: '0g',
    portionSize: '1/2 Cup',
    grams: '124g',
    image: require('../public/images/canned_pear.jpg'),
    category: 'Fruits and vegetables',
  }],
  'orange': [{
    name: 'Orange',
    calories: '80 calories',
    fat: '0g',
    carb: '19g',
    protein: '1g',
    portionSize: '1 Medium orange',
    grams: '154g',
    image: require('../public/images/orange.jpg'),
    category: 'Fruits and vegetables',
  }],
  'salad greens': [{
    name: 'Salad Greens',
    calories: '5 calories',
    fat: '0g',
    carb: '1g',
    protein: '1g',
    portionSize: '1 Cup (Shredded)',
    grams: '154g',
    image: require('../public/images/salad_greens.jpg'),
    category: 'Fruits and vegetables',
  }],
  'blueberry': [{
    name: 'Blueberry',
    calories: '185 calories',
    fat: '0.3g',
    carb: '50.49g',
    protein: '0.92g',
    portionSize: '1 Cup (Shredded)',
    grams: '230g',
    image: require('../public/images/blueberry.jpg'),
    category: 'Fruits and vegetables',
  }],
  'raspberry': [{
    name: 'Raspberry',
    calories: '50 calories',
    fat: '0g',
    carb: '17g',
    protein: '1g',
    portionSize: '1 Cup',
    grams: '125g',
    image: require('../public/images/raspberry.jpg'),
    category: 'Fruits and vegetables',
  }],
  'blackberry': [{
    name: 'Blackberry',
    calories: '60 calories',
    fat: '0.5g',
    carb: '13g',
    protein: '2g',
    portionSize: '1 Cup',
    grams: '140g',
    image: require('../public/images/blackberry.jpg'),
    category: 'Fruits and vegetables',
  }],
  'strawberry': [{
    name: 'Strawberry',
    calories: '46 calories',
    fat: '0g',
    carb: '11g',
    protein: '1g',
    portionSize: '1 Cup',
    grams: '144g',
    image: require('../public/images/strawberry.jpg'),
    category: 'Fruits and vegetables',
  }],
  'kiwifruit': [{
    name: 'Kiwifruit',
    calories: '90 calories',
    fat: '1g',
    carb: '20g',
    protein: '1g',
    portionSize: '2 Medium kiwifruits',
    grams: '148g',
    image: require('../public/images/kiwifruit.jpg'),
    category: 'Fruits and vegetables',
  }],
  'apricot': [{
    name: 'Apricot',
    calories: '70 calories',
    fat: '0.5g',
    carb: '16g',
    protein: '2g',
    portionSize: '4 Apricots',
    grams: '140g',
    image: require('../public/images/apricot.jpg'),
    category: 'Fruits and vegetables',
  }],
  'pineapple': [{
    name: 'Pineapple',
    calories: '50 calories',
    fat: '0g',
    carb: '13g',
    protein: '1g',
    portionSize: '2 Slices',
    grams: '130g',
    image: require('../public/images/pineapple.jpg'),
    category: 'Fruits and vegetables',
  }],
  'pear (nashi)': [{
    name: 'Pear (Nashi)',
    calories: '100 calories',
    fat: '0g',
    carb: '26g',
    protein: '1g',
    portionSize: '1 Medium pear',
    grams: '166g',
    image: require('../public/images/pear.jpg'),
    category: 'Fruits and vegetables',
  }],
  'rockmelon': [{
    name: 'Rockmelon',
    calories: '50 calories',
    fat: '0g',
    carb: '12g',
    protein: '1g',
    portionSize: '1/12 of a melon',
    grams: '166g',
    image: require('../public/images/rockmelon.jpg'),
    category: 'Fruits and vegetables',
  }],
  'watermelon': [{
    name: 'Watermelon',
    calories: '46 calories',
    fat: '0g',
    carb: '12g',
    protein: '1g',
    portionSize: '2 cups diced',
    grams: '166g',
    image: require('../public/images/watermelon.jpg'),
    category: 'Fruits and vegetables',
  }],
  'mango': [{
    name: 'Mango',
    calories: '110 calories',
    fat: '0g',
    carb: '27g',
    protein: '0g',
    portionSize: '1 cup diced',
    grams: '166g',
    image: require('../public/images/mango.jpg'),
    category: 'Fruits and vegetables',
  }],
  'papaya': [{
    name: 'Papaya',
    calories: '55 calories',
    fat: '0g',
    carb: '14g',
    protein: '1g',
    portionSize: '1 cup diced',
    grams: '140g',
    image: require('../public/images/papaya.jpg'),
    category: 'Fruits and vegetables',
  }],
  'capsicum': [{
    name: 'Capsicum',
    calories: '35 calories',
    fat: '0g',
    carb: '7g',
    protein: '1g',
    portionSize: '1 bell pepper',
    grams: '140g',
    image: require('../public/images/capsicum.jpg'),
    category: 'Fruits and vegetables',
  }],
  'grape': [{
    name: 'Grape',
    calories: '90 calories',
    fat: '1g',
    carb: '24g',
    protein: '1g',
    portionSize: '1.5 cup',
    grams: '138g',
    image: require('../public/images/grape.jpg'),
    category: 'Fruits and vegetables',
  }],
  'apricot (dried)': [{
    name: 'Apricot (Dried)',
    calories: '110 calories',
    fat: '0g',
    carb: '25g',
    protein: '1g',
    portionSize: '4 pieces',
    grams: '40g',
    image: require('../public/images/apricot_dried.jpg'),
    category: 'Fruits and vegetables',
  }],
  'raisin (dried)': [{
    name: 'Raisin (Dried)',
    calories: '170 calories',
    fat: '7g',
    carb: '29g',
    protein: '1g',
    portionSize: '34 pieces',
    grams: '40g',
    image: require('../public/images/raisin_dried.jpg'),
    category: 'Fruits and vegetables',
  }],
  'prune (dried)': [{
    name: 'Prune (Dried)',
    calories: '110 calories',
    fat: '0g',
    carb: '25g',
    protein: '1g',
    portionSize: '5 pieces',
    grams: '42g',
    image: require('../public/images/prune_dried.jpg'),
    category: 'Fruits and vegetables',
  }],
  'onion': [{
    name: 'Onion',
    calories: '45 calories',
    fat: '0g',
    carb: '1g',
    protein: '1g',
    portionSize: '1 medium onion',
    grams: '148g',
    image: require('../public/images/onion.jpg'),
    category: 'Fruits and vegetables',
  }],
  'tomato': [{
    name: 'Tomato',
    calories: '25 calories',
    fat: '0g',
    carb: '5g',
    protein: '1g',
    portionSize: '1 medium tomato',
    grams: '148g',
    image: require('../public/images/tomato.jpg'),
    category: 'Fruits and vegetables',
  }],
  'corn': [{
    name: 'Corn',
    calories: '89 calories',
    fat: '1g',
    carb: '21g',
    protein: '3g',
    portionSize: '1/2 cup',
    grams: '82g',
    image: require('../public/images/corn.jpg'),
    category: 'Fruits and vegetables',
  }],
  'broccoli': [{
    name: 'Broccoli',
    calories: '31 calories',
    fat: '0.34g',
    carb: '6.04g',
    protein: '2.57g',
    portionSize: '1 cup chopped',
    grams: '91g',
    image: require('../public/images/broccoli.jpg'),
    category: 'Fruits and vegetables',
  }],
  'carrot': [{
    name: 'Carrot',
    calories: '52 calories',
    fat: '0.3g',
    carb: '12.3g',
    protein: '1.2g',
    portionSize: '1 cup chopped',
    grams: '128g',
    image: require('../public/images/carrot.jpg'),
    category: 'Fruits and vegetables',
  }],
  'potato': [{
    name: 'Potato',
    calories: '110 calories',
    fat: '0g',
    carb: '26g',
    protein: '3g',
    portionSize: '1 potato',
    grams: '148g',
    image: require('../public/images/potato.jpg'),
    category: 'Fruits and vegetables',
  }],
  'kumara': [{
    name: 'Kumara',
    calories: '110 calories',
    fat: '0g',
    carb: '26g',
    protein: '3g',
    portionSize: '1 potato',
    grams: '128g',
    image: require('../public/images/kumara.jpg'),
    category: 'Fruits and vegetables',
  }],
  'pumpkin': [{
    name: 'Pumpkin',
    calories: '130 calories',
    fat: '6g',
    carb: '15g',
    protein: '3g',
    portionSize: '3/4 cup diced',
    grams: '65g',
    image: require('../public/images/pumpkin.jpg'),
    category: 'Fruits and vegetables',
  }],
  'yoghurt': [{
    name: 'Yoghurt',
    calories: '150 calories',
    fat: '4.5g',
    carb: '20g',
    protein: '8g',
    portionSize: '1 cup',
    grams: '150g',
    image: require('../public/images/yoghurt.jpg'),
    category: 'Milk and milk products',
  }],
  'cheese (mozzarella)': [{
    name: 'Cheese (Mozzarella)',
    calories: '80 calories',
    fat: '5g',
    carb: '1g',
    protein: '8g',
    portionSize: '1/3 cup',
    grams: '30g',
    image: require('../public/images/mozzarella.jpg'),
    category: 'Milk and milk products',
  }],
  'cheese (parmesan)': [{
    name: 'Cheese (Parmesan)',
    calories: '100 calories',
    fat: '7g',
    carb: '1g',
    protein: '9g',
    portionSize: '1/4 cup',
    grams: '28g',
    image: require('../public/images/parmesan.jpg'),
    category: 'Milk and milk products',
  }],
  'cheese (cheddar)': [{
    name: 'Cheese (Cheddar)',
    calories: '100 calories',
    fat: '6g',
    carb: '7g',
    protein: '1g',
    portionSize: '1/4 cup',
    grams: '28g',
    image: require('../public/images/cheddar.jpg'),
    category: 'Milk and milk products',
  }],
  'milk (full fat)': [{
    name: 'Milk (Full fat)',
    calories: '190 calories',
    fat: '9g',
    carb: '13g',
    protein: '9g',
    portionSize: '1 cup',
    grams: '',
    mls: '240ml',
    image: require('../public/images/milk_fullfat.jpg'),
    category: 'Milk and milk products',
  }],
  'milk (trim)': [{
    name: 'Milk (Trim)',
    calories: '90 calories',
    fat: '0g',
    carb: '13g',
    protein: '9g',
    portionSize: '1 cup',
    grams: '',
    mls: '240ml',
    image: require('../public/images/milk_trim.jpg'),
    category: 'Milk and milk products',
  }],
  'milk (lite)': [{
    name: 'Milk (Lite)',
    calories: '90 calories',
    fat: '0g',
    carb: '13g',
    protein: '9g',
    portionSize: '1 cup',
    grams: '',
    mls: '240ml',
    image: require('../public/images/milk_lite.jpg'),
    category: 'Milk and milk products',
  }],
  'cheese (paneer)': [{
    name: 'Cheese (Paneer)',
    calories: '98 calories',
    fat: '4.3g',
    carb: '3.38g',
    protein: '11.12g',
    portionSize: 'NEED SOMETHING FOR THIS',
    grams: '100g',
    image: require('../public/images/paneer.jpg'),
    category: 'Milk and milk products',
  }],
  'cheese (feta)': [{
    name: 'Cheese (Feta)',
    calories: '80 calories',
    fat: '6g',
    carb: '1g',
    protein: '5g',
    portionSize: '1/4 cups',
    grams: '28g',
    image: require('../public/images/feta.jpg'),
    category: 'Milk and milk products',
  }],
  'cream cheese': [{
    name: 'Cream Cheese',
    calories: '80 calories',
    fat: '4g',
    carb: '10g',
    protein: '1g',
    portionSize: '2 Tablespoons',
    grams: '33g',
    image: require('../public/images/cream_cheese.png'),
    category: 'Milk and milk products',
  }],
  'muffin': [{
    name: 'Muffin',
    calories: '210 calories',
    fat: '10g',
    carb: '28g',
    protein: '3g',
    portionSize: '1/2 muffin',
    grams: '57g',
    image: require('../public/images/muffin.jpg'),
    category: 'Occasional foods',
  }],
  'chips': [{
    name: 'Chips',
    calories: '160 calories',
    fat: '10g',
    carb: '15g',
    protein: '2g',
    portionSize: '15 chips',
    grams: '28g',
    image: require('../public/images/chips.jpg'),
    category: 'Occasional foods',
  }],
  'pringles': [{
    name: 'Pringles',
    calories: '150 calories',
    fat: '9g',
    carb: '15g',
    protein: '1g',
    portionSize: '16 chips',
    grams: '28g',
    image: require('../public/images/pringles.jpg'),
    category: 'Occasional foods',
  }],
  'shapes': [{
    name: 'Shapes',
    calories: '117 calories',
    fat: '4.5g',
    carb: '15.2g',
    protein: '3.4g',
    portionSize: '7 chips',
    grams: '25g',
    image: require('../public/images/shapes.jpg'),
    category: 'Occasional foods',
  }],
  'brownie': [{
    name: 'Brownie',
    calories: '450 calories',
    fat: '27g',
    carb: '50g',
    protein: '8g',
    portionSize: '1 brownie',
    grams: '102g',
    image: require('../public/images/brownie.jpg'),
    category: 'Occasional foods',
  }],
  'apple pie': [{
    name: 'Apple Pie',
    calories: '340 calories',
    fat: '17g',
    carb: '45g',
    protein: '2g',
    portionSize: '1/8 pie',
    grams: '131g',
    image: require('../public/images/apple_pie.jpg'),
    category: 'Occasional foods',
  }],
  'ice cream cone': [{
    name: 'Ice Cream Cone',
    calories: '12 calories',
    fat: '0g',
    carb: '2g',
    protein: '0g',
    portionSize: '1 cone',
    grams: '3g',
    image: require('../public/images/icecream_cone.png'),
    category: 'Occasional foods',
  }],
  'lasagna': [{
    name: 'Lasagna',
    calories: '200 calories',
    fat: '1g',
    carb: '41g',
    protein: '7g',
    portionSize: 'Half of deck of cards',
    grams: '57g',
    image: require('../public/images/lasagna.jpg'),
    category: 'Occasional foods',
  }],
  'pizza': [{
    name: 'Pizza',
    calories: '330 calories',
    fat: '13g',
    carb: '40g',
    protein: '14g',
    portionSize: '1/6 pizza',
    grams: '129g',
    image: require('../public/images/pizza.jpg'),
    category: 'Occasional foods',
  }],
  'muesli bar': [{
    name: 'Muesli Bar',
    calories: '140 calories',
    fat: '3.5g',
    carb: '25g',
    protein: '2g',
    portionSize: '1 bar',
    grams: '33g',
    image: require('../public/images/muesli_bar.jpg'),
    category: 'Occasional foods',
  }],
  'tim tams': [{
    name: 'Tim tams',
    calories: '280 calories',
    fat: '19g',
    carb: '26g',
    protein: '5g',
    portionSize: '3 pieces',
    grams: '59g',
    image: require('../public/images/timtam.jpg'),
    category: 'Occasional foods',
  }],
  'steak and cheese pie': [{
    name: 'Steak and cheese pie',
    calories: '670 calories',
    fat: '41g',
    carb: '56g',
    protein: '20g',
    portionSize: '1 pie',
    grams: '283g',
    image: require('../public/images/steak_and_cheese_pie.jpg'),
    category: 'Occasional foods',
  }],
  'cup ramen': [{
    name: 'Cup ramen',
    calories: '300 calories',
    fat: '13.8g',
    carb: '37.6g',
    protein: '6.1g',
    portionSize: '1 container',
    grams: '768g',
    image: require('../public/images/cup_ramen.jpg'),
    category: 'Occasional foods',
  }],
  'chicken nuggets': [{
    name: 'Chicken nuggets',
    calories: '200 calories',
    fat: '10g',
    carb: '13g',
    protein: '13g',
    portionSize: '5 nuggets',
    grams: '84g',
    image: require('../public/images/chicken_nugget.jpg'),
    category: 'Occasional foods',
  }],
  'french fries': [{
    name: 'French Fries',
    calories: '64 calories',
    fat: '3.6g',
    carb: '7.5g',
    protein: '0.75g',
    portionSize: '12 fries',
    grams: '22.5g',
    image: require('../public/images/french_fries.jpg'),
    category: 'Occasional foods',
  }],
  'oil': [{
    name: 'Oil',
    calories: '120 calories',
    fat: '14g',
    carb: '0g',
    protein: '0g',
    portionSize: '1 Tablespoon',
    grams: '15g',
    image: require('../public/images/oil.jpg'),
    category: 'Extra',
  }],
  'butter': [{
    name: 'Butter',
    calories: '110 calories',
    fat: '12g',
    carb: '0g',
    protein: '0g',
    portionSize: '1 Tablespoon',
    grams: '14g',
    image: require('../public/images/butter.jpg'),
    category: 'Extra',
  }],
  'salad dressing': [{
    name: 'Salad dressing',
    calories: '180 calories',
    fat: '14g',
    carb: '14g',
    protein: '2g',
    portionSize: '4 Tablespoon',
    grams: '63g',
    image: require('../public/images/salad_dressing.jpg'),
    category: 'Extra',
  }],
  'up and go': [{
    name: 'Up and Go',
    calories: '260 calories',
    fat: '9g',
    carb: '46g',
    protein: '2g',
    portionSize: '1 carton',
    grams: '63g',
    image: require('../public/images/upandgo.jpg'),
    category: 'Extra',
  }],
  'water': [{
    name: 'Water',
    calories: '2 calories',
    fat: '0g',
    carb: '0g',
    protein: '0g',
    portionSize: '1 cup',
    grams: '',
    mls: '330ml',
    image: require('../public/images/water.jpg'),
    category: 'Extra',
  }],
  'wine': [{
    name: 'Wine',
    calories: '85 calories',
    fat: '0g',
    carb: '2.8g',
    protein: '0.1g',
    portionSize: '1 glass',
    grams: '103g',
    image: require('../public/images/wine.jpg'),
    category: 'Extra',
  }],
  'spirits': [{
    name: 'Spirits',
    calories: '142 calories',
    fat: '0g',
    carb: '9.6g',
    protein: '1.8g',
    portionSize: '1.5 cups',
    grams: '103g',
    image: require('../public/images/spirits.jpg'),
    category: 'Extra',
  }],
  'beer': [{
    name: 'Beer',
    calories: '150 calories',
    fat: '0g',
    carb: '13g',
    protein: '1g',
    portionSize: '1 beer',
    grams: '103g',
    image: require('../public/images/beer.jpg'),
    category: 'Extra',
  }],
  'coffee (mochaccino)': [{
    name: 'Coffee (Mochaccino)',
    calories: '212 calories',
    fat: '4.5g',
    carb: '19g',
    protein: '24g',
    portionSize: '1 cup',
    grams: '453.6g',
    image: require('../public/images/mochaccino.jpg'),
    category: 'Extra',
  }],
  'coke': [{
    name: 'Coke',
    calories: '140 calories',
    fat: '0g',
    carb: '39g',
    protein: '0g',
    portionSize: '1 can',
    grams: '',
    mls: '240ml',
    image: require('../public/images/coke.jpg'),
    category: 'Extra',
  }],
  'diet coke': [{
    name: 'Diet coke',
    calories: '0 calories',
    fat: '0g',
    carb: '1g',
    protein: '0g',
    portionSize: '1 can',
    grams: '',
    mls: '240ml',
    image: require('../public/images/diet_coke.jpg'),
    category: 'Extra',
  }],
  'sprite': [{
    name: 'Sprite',
    calories: '210 calories',
    fat: '0g',
    carb: '56g',
    protein: '0g',
    portionSize: '1 can',
    grams: '',
    mls: '240ml',
    image: require('../public/images/sprite.jpg'),
    category: 'Extra',
  }],
  'coconut water': [{
    name: 'Coconut water',
    calories: '100 calories',
    fat: '0g',
    carb: '25.4g',
    protein: '0g',
    portionSize: '1 can',
    grams: '',
    mls: '240ml',
    image: require('../public/images/coconut_water.jpg'),
    category: 'Extra',
  }],
  'coconut milk': [{
    name: 'Coconut Milk',
    calories: '100 calories',
    fat: '10g',
    carb: '2g',
    protein: '1g',
    portionSize: '1/4 cup',
    grams: '',
    mls: '60ml',
    image: require('../public/images/coconut_milk.jpg'),
    category: 'Extra',
  }],
  'almond milk': [{
    name: 'Almond Milk',
    calories: '35 calories',
    fat: '2.5g',
    carb: '2g',
    protein: '1g',
    portionSize: '1 cup',
    grams: '',
    mls: '240ml',
    image: require('../public/images/almond_milk.jpg'),
    category: 'Extra',
  }],
  'soy milk': [{
    name: 'Soy Milk',
    calories: '90 calories',
    fat: '4.5g',
    carb: '4g',
    protein: '9g',
    portionSize: '1 cup',
    grams: '',
    mls: '240ml',
    image: require('../public/images/soy_milk.jpg'),
    category: 'Extra',
  }],
}

export default class Tabbed extends React.Component {

  constructor(props) {
    super(props);
    this.state = {
      slideIndex: 0,
      searchText: '',
      trueText:'',
      foodArray: [],
    };
  }

  state = {
    simple: '',
  };

  handleChange = (value) => {
    this.setState({
      slideIndex: value,
      showFoodCard: false,
    });
  };

  onNewRequest = (chosenRequest, index) => {
    this.setState({
      searchText: chosenRequest,
    });
    var foodObject = FoodMap[chosenRequest.toLowerCase()];
    if(foodObject != null && !this.state.foodArray.includes(chosenRequest.toLowerCase())) {
      var newArray = this.state.foodArray.slice();
      newArray.unshift(chosenRequest.toLowerCase());
      this.setState({
        trueText: chosenRequest,
        foodArray: newArray,
        showFoodCard: true,
      });
    }

  }

  clearAll = () => {
    var newArray = [];
    this.setState({
      foodArray: newArray,
      showFoodCard: false,
    })

  }

  clearCard = (card) => {

      var newArray = this.state.foodArray;
      var index = newArray.indexOf(card);
      console.log(card);
      console.log(newArray);
      newArray.splice(index, 1);

      this.setState({
        foodArray: newArray,
      });

  }

  // returnFoodCards = () => {
  //   console.log(this.state.foodArray);
  //   this.state.foodArray.forEach(function(food) {
  //     return(foodCards.push(<FoodCard obj={FoodMap[food.toLowerCase()]} />));
  //   })
  // }

  render() {
    return (
      <div style={{}}>
        <Tabs
          onChange={this.handleChange}
          value={this.state.slideIndex}
          inkBarStyle={{ height:'4px', marginTop:'-4px' }}
        >
          <Tab label="What are the food groups?" value={0} />
          <Tab label="What is a healthy plate model?" value={1} />
          <Tab label="How much is one serving?" value={2} />
        </Tabs>
        <SwipeableViews
          index={this.state.slideIndex}
          onChangeIndex={this.handleChange}
        >
          <div>
            <FoodGroupTab />
          </div>
          <div style={{ margin:'1rem' }}>
          <h1>What is a healthy plate model?</h1>
            <img src={require("../public/images/healthy.png")} style={{ margin:'0 auto', display:'block', width:'40%', float:'right' }}/>
            <p>
              A healthy plate model consists of 3 parts. The starchy carbohydrate takes up 1/4 of the plate, the protein food takes up 1/4 of the plate and vegetables takes up the remaining 1/2.
            </p>
            <h3>Examples</h3>
            <p><b>Starchy carbohydrates</b>: potato, kumara, rice, pasta, grains, corn, taro, parsnip</p>
            <p><b>Protein foods</b>: lean meats, fish, seafood, eggs, baked beans</p>
            <p><b>Vegetables</b>: salad vegetables, carrot, capsicum, pumpkin, onion</p>

          </div>
          <div>
          <FlatButton label="Clear All" secondary={true} fullWidth={true} labelStyle={{ fontSize:'20px' }} onTouchTap={this.clearAll.bind(this)}/>
            <div style={styles.slide} style={{ textAlign:'center', marginTop:'5rem' }}>

              <AutoComplete
                floatingLabelText="Enter a food!"
                filter={AutoComplete.fuzzyFilter}
                dataSource={foods}
                maxSearchResults={5}
                onNewRequest={ this.onNewRequest.bind(this) }
                searchText={this.state.searchText}
                textFieldStyle={{fontSize:'32px', lineHeight:'32px', height:'92px'}}
              />
              <ReactCSSTransitionGroup
                transitionName = "example"
                transitionEnterTimeout={700} transitionLeaveTimeout={300}
                transitionAppear={true}
                transitionAppearTimeout={500} component='div'>
                {
                  this.state.showFoodCard &&
                  this.state.foodArray.map(food => {
                      return(

                        <FoodCard obj={FoodMap[food.toLowerCase()]} key={food} clearCard={this.clearCard.bind(this)} style={{opacity:'0', transition:'opacity 1s ease-in-out'}}/>
                      );
                  })
                }
              </ReactCSSTransitionGroup >

            </div>
          </div>
        </SwipeableViews>
      </div>
    );
  }
}
